language: go
go:
- 1.x
#- 1.10.x
#- master
sudo: false
install:
- go get github.com/jonas-p/go-shp
- go get github.com/paulmach/go.geojson
- go get golang.org/x/text/encoding/charmap
cache: 
  directories: 
    - data/downloaded
env:
  global:
  - secure: Yb5rK6QhQtcUjEzhpMCuDUtXi7mvZ61xAzCz0R2/GHCekGq0m+Ov9pYuuOP47rM2+J4RX8XsCsszyk7dBqY44UJw/kSmlgyfrrSqz/3ad75Xyrv4BnaI8oEBfJTR/5eGte0CfI0ZngN78bVh/cFkW0gB0vibd2wpsdVFash5F6eAstgc+Xy8V5P+ABfSHoZuvvo2dHat047AYv3hU/fX44aS/+2ZPdhtpgJvAi7/R4TDyV1J2wM6T+XTUDOh3yDczKwfpUGfT1mf/7rF4b5YNKTGGcMeis8nzZNINpTBH9+H7I7q2g6wr5vXJKaOUaAh6ev9dHbJGG7ydiRLzGEewD+mtriCsEhf44q2NARRsbCeWgb2zk7KkKk9Dw1QXUO5X27PPfjQxffYpRM3sEr9DjEFkczmwphmMEi/Dw0l/iPtbHsanKPpWvXyyFkm9FsCUfWbTOuQ0jbjXXsDw/rOMd6WYNBkGCREuz7Y2Yz6vZ+ROXYPLdrBo0Lv9q23eOo/akYMsr9gau56+yaDBdzrblBUNzJI1l6sw90hH3+bpAATuDyOTU9gv99FTL9zI5VLQRRJeVE3xuduP6hyOzDkUpFKSo31Nh/uhzpIburVn1UB2MCF2zOSFeAIEZgSwgGGXLbNFXzj8Ty/zcv4P6o6fKnkoM5BA1hmfSFaXM3dzPI=
  - secure: AdcRG7BLZKq71xkF2ceeKleXwiB75rsva+L43RGb41ykKKyhvAcfqmQ/aE+3JsLyC2lFqgB12udNfLcLur3NWn260IWJ/9IH17uoHpNqs9UDYZHCde+5vIHM0gQHRoP3gaCOFyD2wXmGUCS1dVDoSCAXtYo+2io7yCwKUuYnyhOB9FIvCo6V5ryqKRNW4xIHv2h34Y9bt55cTjnLpuUdtT1twVhmLcURy11FyETo+YmhqcSebC3Pm/S4ablSCTY/ro8WHimD2LCsSStnOjNn0QYY4JEgMT3zLnGx2eJdyfTBlRgeDj9lS6ph6QsW+5DTLpY974Vlx7Y6HehbiW68KQlB7Z397I0NxPVGG9XuEf8eMsf3Jmw59roYMHN6aZ/YQELKB65lcfkvkmEAsT7oAJu6U6tkVhcRrgXz2uGoxdsqG5IvivKQOLmg7Yp3uiCcDQl8fKW4RyyN+sn9k0lBTJBT4VKn2lDASvUr2lh5lCRkKYPCQOdy5j7zOhiYnnAuOrFSlbQsZoDnSZPokb8uwnSSwTjSiMyO2VNtNZk/YqLCkhiZiawOTu0khVEB/j6S1pBFm5aHGcYSviVWRCp+V5pIi+A+lO8oImgu3kRlXM+FZz52G9J3IF1bnYkyxTaEJaIFqU1MU6iyn9DG65YUACBnkQ0igZjj8f2oETMX3Uo=
script:
- make
# - make bench
- ls -la data
- ls -la data/downloaded
- ls -la data/slovenia/*
after_success:
- bash <(curl -s https://codecov.io/bash)
